### ISSUE TITLE
Error when trying to run the script

### ISSUE THREAD

**Issue by benblaine** [markfguerra/google-forms-to-slack#1]
Thanks for this and the nice setup guide. I unfortunately get an error when I try run it:

TypeError: Cannot read property "namedValues" from undefined. (line 37, file "Code")

**Comment by benblaine** [comment]
I'm an idiot. I realised I didn't uncomment the test code. Thanks for this, works great!

**Comment by markfguerra** [comment]
Awesome! I hope it has been helpful for you and your slack team.
