### ISSUE TITLE
Issues when initializing

### ISSUE THREAD

**Issue by theonlytruebigmac** [markfguerra/google-forms-to-slack#4]
Cannot call overloaded constructor forSpreadsheet with parameters (null) because there is more than one matching constructor signature: interface SpreadsheetTriggerBuilder forSpreadsheet(String) interface SpreadsheetTriggerBuilder forSpreadsheet(Spreadsheet) (line 36, file "Code")

**Comment by markfguerra** [comment]
Sounds like perhaps you have no parameter (or null) in your call to the function forSpreadsheet(). I'd suggest that you have a closer look at your initialize() function. It's a little hard to tell exactly what's going on without seeing your modified code, though.

**Comment by theonlytruebigmac** [comment]
It looks like it highlights the '.create();' when it errors out. I'm not sure what I was doing wrong, I followed your readme and only updated the items in the customize section.

`// Alter this to match the incoming webhook url provided by Slack
var slackIncomingWebhookUrl = 'https://hooks.slack.com/services/MYURL';

// Include # for public channels, omit it for private channels
var postChannel = "#alerts";

var postIcon = ":mailbox_with_mail:";
var postUser = "Form Response";
var postColor = "#0000DD";

var messageFallback = "The attachment must be viewed as plain text.";
var messagePretext = "A user submitted a response to the form.";

///////////////////////
// End customization //
///////////////////////

// In the Script Editor, run initialize() at least once to make your code execute on form submit
function initialize() {
  var triggers = ScriptApp.getProjectTriggers();
  for (var i in triggers) {
    ScriptApp.deleteTrigger(triggers[i]);
  }
  ScriptApp.newTrigger("submitValuesToSlack")
    .forSpreadsheet(SpreadsheetApp.getActiveSpreadsheet())
    .onFormSubmit()
    .create();
}`
