### ISSUE TITLE
Posting to Channel Twice

### ISSUE THREAD

**Issue by andrewmsboyd** [markfguerra/google-forms-to-slack#5]
Howdy! Love the project! I'm seeing two posts in the specified channel when my Google Form is submitted. I think this may be because I ran the Initialize function twice by accident?

Do I need to remove the script from the GSheet and add it again? Or is there a better way to resolve this?

Thank you.

**Comment by markfguerra** [comment]
Hey! Thanks for using it :)

As it is written today, running initialize() will delete all triggers and create a trigger on the form submit event, setting it to call the function `submitValuesToSlack`. So I think running it twice won't duplicate the trigger.

You may want to try manually deleting the trigger, just to see what happens when the form gets submitted.

It's possible you have some other duplication somewhere. Do you perhaps have 2 scripts running? There's a script editor for the Google Form, but separately there's a script editor for the Google Sheet that holds the responses. When I wrote this script, I intended it to be used with the Google Sheet.

**Comment by andrewmsboyd** [comment]
Hey sorry for the delay, I've been unplugged for a bit.

I'm fairly certain I only have the one script running from the responses GSheet. Opening the script editor on the Form itself only shows an empty declaration of `myFunction()`.

On the responses GSheet I only have "Code.gs" which contains your code (modified for my Workspace, of course).

Here's an example of the issue in our Slack workspace:
![google-form-to-slack-doublePost](https://user-images.githubusercontent.com/12451628/58340204-e5b60a80-7e10-11e9-889f-4d8b3359b0fa.png)

It looks like it's delivering an empty payload before the real payload arrives...weird.

Would the best course of action just be to delete the script from the sheet and start from scratch?

**Comment by markfguerra** [comment]
> Would the best course of action just be to delete the script from the sheet and start from scratch?

Sounds reasonable. The other option is to diff it against my original version and carefully inspect any changes.

**Comment by markfguerra** [comment]
Since this doesn't seem to be broken in the original code, I'm going to close this issue.

Regardless @andrewmsboyd feel free to post here again if you'd like more assistance working it out.

**Comment by andrewmsboyd** [comment]
I believe I am going to simply delete and re-add the script from the GSheet as was previously mentioned, but in the interest of thoroughness I did indeed run a diff on the original code and mine. It seems as though there is no difference other than the obvious changes to declare variables specific to our workspace.

Output of `diff code.js my_code.js`:

```11c11
< var slackIncomingWebhookUrl = 'https://hooks.slack.com/services/YOUR-URL-HERE';
---
> var slackIncomingWebhookUrl = 'https://hooks.slack.com/services/REDACTED-WEBHOOK-STRING';
14c14
< var postChannel = "YOUR-CHANNEL-HERE";
---
> var postChannel = "#operations-team";
16c16
< var postIcon = ":mailbox_with_mail:";
---
> var postIcon = ":exclamation:";
21c21
< var messagePretext = "A user submitted a response to the form.";
---
> var messagePretext = "Third-party technician has completed work on a device.";```

Thanks again for the help and for writing a neat little tool!
